server:
  port: 8081
  servlet:
    # 给所有controller的url增加/data前缀
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocr?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #connection-test-query: SELECT 1

ocr:
  service:
    paddleSource: test
    baiduSource:
      appID: test
      apiKey: test
      secretKey: test